plugins {
    id "com.gtnewhorizons.gtnhconvention"
}

ext.buildnumber = ""
if (System.getenv().BUILD_NUMBER)
    ext.buildnumber = "-" + System.getenv().BUILD_NUMBER

version = "${minecraftVersion}-${mod_version}${buildnumber}"
group = "uk.joshiejack.mariculture"
archivesBaseName = "Mariculture-Deluxe"

repositories {
    maven {
        name = "chickenbones"
        url = "https://chickenbones.net/maven/"
    }
}
